{% set name = "neuraloperator" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neuraloperator-{{ version }}.tar.gz
  sha256: 9c52ebb00575dd726bae0e7c2fa712a5e2485e30cd134a01eefb887902fdda80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - wandb
    - ruamel_yaml
    - configmypy
    - tensorly
    - tensorly-torch
    - torch-harmonics ==0.7.3
    - matplotlib-base
    - numpy >=1.25
    - opt-einsum
    - h5py
    - zarr

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neuraloperator/neuraloperator
  summary: 'NeuralOperator: Learning in Infinite Dimensions'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
